### ISSUE TITLE
SyntaxWarning

### ISSUE THREAD

**Issue by pankajsharmaml** [errolPereira/Semi-Automatic-Image-Annotation-Tool#12]
Thanks for this package. Getting this error in run python main.py 

main.py:627: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if self.textBox.get() is not '':

**Comment by errolPereira** [comment]
Hi @pankajsharmaml ,
Can you please give details on the machine and environment you are using.
OS :
python version:
conda version:

Thanks.

**Comment by pankajsharmaml** [comment]
OS: Windows 10 Pro
Python: 3.6 in Virtual environment
Conda: 4.10.3

errors:

(label) C:\Users\panka\Desktop\Semi-Automatic-Image-Annotation-Tool>python main.py
Using TensorFlow backend.
2021-09-27 13:17:42.955447: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2021-09-27 13:17:42.955692: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From C:\Users\panka\anaconda3\envs\label\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From main.py:47: The name tf.keras.backend.set_session is deprecated. Please use tf.compat.v1.keras.backend.set_session instead.

2021-09-27 13:17:45.525198: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-09-27 13:17:45.529210: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2021-09-27 13:17:45.529445: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2021-09-27 13:17:45.535159: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-LPNQNUC
2021-09-27 13:17:45.535526: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-LPNQNUC
WARNING:tensorflow:From C:\Users\panka\anaconda3\envs\label\lib\site-packages\keras\backend\tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From C:\Users\panka\anaconda3\envs\label\lib\site-packages\keras\backend\tensorflow_backend.py:4409: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

WARNING:tensorflow:From C:\Users\panka\anaconda3\envs\label\lib\site-packages\keras\backend\tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From C:\Users\panka\anaconda3\envs\label\lib\site-packages\keras\backend\tensorflow_backend.py:2139: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.

WARNING:tensorflow:From C:\Users\panka\anaconda3\envs\label\lib\site-packages\keras\backend\tensorflow_backend.py:4267: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:From C:\Users\panka\anaconda3\envs\label\lib\site-packages\keras\backend\tensorflow_backend.py:4479: The name tf.truncated_normal is deprecated. Please use tf.random.truncated_normal instead.

WARNING:tensorflow:From C:\Users\panka\anaconda3\envs\label\lib\site-packages\keras_retinanet\backend\tensorflow_backend.py:44: The name tf.image.resize_images is deprecated. Please use tf.image.resize instead.

WARNING:tensorflow:From C:\Users\panka\anaconda3\envs\label\lib\site-packages\keras_retinanet\backend\tensorflow_backend.py:68: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From C:\Users\panka\anaconda3\envs\label\lib\site-packages\keras\backend\tensorflow_backend.py:190: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

WARNING:tensorflow:From C:\Users\panka\anaconda3\envs\label\lib\site-packages\keras\backend\tensorflow_backend.py:197: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From C:\Users\panka\anaconda3\envs\label\lib\site-packages\keras\backend\tensorflow_backend.py:203: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From C:\Users\panka\anaconda3\envs\label\lib\site-packages\keras\backend\tensorflow_backend.py:207: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From C:\Users\panka\anaconda3\envs\label\lib\site-packages\keras\backend\tensorflow_backend.py:216: The name tf.is_variable_initialized is deprecated. Please use tf.compat.v1.is_variable_initialized instead.

WARNING:tensorflow:From C:\Users\panka\anaconda3\envs\label\lib\site-packages\keras\backend\tensorflow_backend.py:223: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.

Traceback (most recent call last):
  File "main.py", line 62, in <module>
    model_yolo = load_model(yolo_path)
  File "C:\Users\panka\anaconda3\envs\label\lib\site-packages\keras\engine\saving.py", line 458, in load_wrapper
    return load_function(*args, **kwargs)
  File "C:\Users\panka\anaconda3\envs\label\lib\site-packages\keras\engine\saving.py", line 549, in load_model
    with H5Dict(filepath, mode='r') as h5dict:
  File "C:\Users\panka\anaconda3\envs\label\lib\site-packages\keras\utils\io_utils.py", line 191, in __init__
    self.data = h5py.File(path, mode=mode)
  File "C:\Users\panka\anaconda3\envs\label\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "C:\Users\panka\anaconda3\envs\label\lib\site-packages\h5py\_hl\files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '.\snapshots\yolo.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by errolPereira** [comment]
@pankajsharmaml You need to save the yolo.h5 weights files in the snapshots folder. The error is saying that currently, it is not able to find any such file.

**Comment by errolPereira** [comment]
Issue resolved
