### ISSUE TITLE
OSError: Unable to open file (file signature not found)

### ISSUE THREAD

**Issue by 7eta** [errolPereira/Semi-Automatic-Image-Annotation-Tool#8]
I changed the name of yolov3.weights to yolo.h5 but not working

Traceback (most recent call last):
  File "main.py", line 62, in <module>
    model_yolo = load_model(yolo_path)
  File "C:\Anaconda3\envs\semi_36\lib\site-packages\keras\engine\saving.py", line 458, in load_wrapper
    return load_function(*args, **kwargs)
  File "C:\Anaconda3\envs\semi_36\lib\site-packages\keras\engine\saving.py", line 549, in load_model
    with H5Dict(filepath, mode='r') as h5dict:
  File "C:\Anaconda3\envs\semi_36\lib\site-packages\keras\utils\io_utils.py", line 191, in __init__
    self.data = h5py.File(path, mode=mode)
  File "C:\Anaconda3\envs\semi_36\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "C:\Anaconda3\envs\semi_36\lib\site-packages\h5py\_hl\files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

My desktop OS windows 10 Home, python 3.6
I changed the version of h5py 3.1.0 to 2.1.0 because showed me < AttributeError: 'str' object has no attribute 'decode' >

please help

**Comment by 7eta** [comment]
Oh... I downloaded yolo.h5 from other site, 
it worked.

**Comment by 7eta** [comment]
> I changed the name of yolov3.weights to yolo.h5 but not working
> 
> Traceback (most recent call last):
> File "main.py", line 62, in
> model_yolo = load_model(yolo_path)
> File "C:\Anaconda3\envs\semi_36\lib\site-packages\keras\engine\saving.py", line 458, in load_wrapper
> return load_function(*args, **kwargs)
> File "C:\Anaconda3\envs\semi_36\lib\site-packages\keras\engine\saving.py", line 549, in load_model
> with H5Dict(filepath, mode='r') as h5dict:
> File "C:\Anaconda3\envs\semi_36\lib\site-packages\keras\utils\io_utils.py", line 191, in **init**
> self.data = h5py.File(path, mode=mode)
> File "C:\Anaconda3\envs\semi_36\lib\site-packages\h5py_hl\files.py", line 408, in **init**
> swmr=swmr)
> File "C:\Anaconda3\envs\semi_36\lib\site-packages\h5py_hl\files.py", line 173, in make_fid
> fid = h5f.open(name, flags, fapl=fapl)
> File "h5py_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
> File "h5py_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
> File "h5py\h5f.pyx", line 88, in h5py.h5f.open
> OSError: Unable to open file (file signature not found)
> 
> My desktop OS windows 10 Home, python 3.6
> I changed the version of h5py 3.1.0 to 2.1.0 because showed me < AttributeError: 'str' object has no attribute 'decode' >
> 
> please help
